Repository sangyong-99/Team-ARTX-PoliceScience, pull requests merged in 2023-10, with the labels that each got.

#4 [Chore] Create dummy data in JSON format
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/example.json
Labels: :hammer: Chore

#11 Add ColorSet, Font
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/BarPoint.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/BgBlue.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/BgGradient.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/PointDarkGray.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/PointGold.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/PointGray.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/PrimaryBlack.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/TextBlue.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/TextRed.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/BG GroupedPrimary.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/BG GroupedSecondary.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/ColorsBlue.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/ColorsRed.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/GraysGray 5.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/GraysGray 6.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/GraysWhite.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/MaterialsChrome.colorset/Contents.json
Labels: ✨ Feature

#15 Setting View Base
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/AppDelegate.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/BG GroupedPrimary.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Firestore/FirestoreManager.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Model/SettingModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/UserDefault/LocalState.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/UINavigationController+Util.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/SettingViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/SettingViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/RegisSettingTableViewCell.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/SettingTableViewCell.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/SettingViewAlert.swift
Labels: ✨ Feature

#14 Add BookView
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Thumbnail.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Thumbnail.imageset/Thumbnail 1.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Thumbnail.imageset/Thumbnail 2.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Thumbnail.imageset/Thumbnail.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/policeStudiesBasicImage.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/policeStudiesBasicImage.imageset/policeStudiesBasicImage.jpeg
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/policeStudiesPastExamImage.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/policeStudiesPastExamImage.imageset/policeStudiesPastExamImage.jpeg
  ARTX-PoliceScience/ARTX-PoliceScience/Model/Book.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/Books.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/BookViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/BookTableViewCell.swift
Labels: ✨ Feature

#19 Connect BookView, SettingView
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/AppDelegate.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Thumbnail.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Thumbnail.imageset/Thumbnail 1.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Thumbnail.imageset/Thumbnail 2.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Thumbnail.imageset/Thumbnail.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Thumbnail.imageset/Thumbnail@2x.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Thumbnail.imageset/Thumbnail@3x.png
  ARTX-PoliceScience/ARTX-PoliceScience/Firestore/FirestoreManager.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/UINavigationController+Util.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/SettingViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/SettingViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/BookTableViewCell.swift
Labels: ✨ Feature

#26 Feature/#13 Add Bookview
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookViewController.swift
Labels: ✨ Feature

#29 Feature/#12 add quizview
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/UserDefault/Utils/UINavigationController+Util.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/SettingViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView.swift
Labels: 🍱 Add

#28 Feature/#2 home view base
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/homeBG.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/homeBG.imageset/homeBG.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/iconCompletion-off.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/iconCompletion-off.imageset/iconCompletion-off.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/iconCompletion-on.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/iconCompletion-on.imageset/iconCompletion-on.png
  ARTX-PoliceScience/ARTX-PoliceScience/Model/HomeModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Model/QuizModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/HomeViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeView/HomeTableCellView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeView/HomeTableHeaderView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeView/HomeTableSectionHeaderView.swift
Labels: ✨ Feature

#43 Feat/#9 add bookmark func
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookmarkViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/BookmarkViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/BookmarkView/BookmarkEmptyTableViewCell.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/BookmarkView/BookmarkTableViewCell.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/BookmarkView/BookmarkTableViewHeader.swift
Labels: ✨ Feature

#47 [Add] Vector Images (icon, badge, button)
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/bgObject.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/bgObject.imageset/bgObject.svg
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/button-false.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/button-false.imageset/button-false.svg
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/button-true.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/button-true.imageset/button-true.svg
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/gradeBadge-0.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/gradeBadge-0.imageset/gradeBadge-0.svg
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/gradeBadge-1.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/gradeBadge-1.imageset/gradeBadge-1.svg
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/gradeBadge-2.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/gradeBadge-2.imageset/gradeBadge-2.svg
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/iconCompletion-false.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/iconCompletion-false.imageset/iconCompletion-false.svg
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/iconCompletion-true.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/VectorImages/iconCompletion-true.imageset/iconCompletion-true.svg
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/iconCompletion-off.imageset/iconCompletion-off.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/iconCompletion-on.imageset/iconCompletion-on.png
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/HomeViewModel.swift
Labels: 🍱 Add

#44 [Fix] Fix typo
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookmarkViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/BookmarkViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/BookmarkView/PartTitleLabel.swift
Labels: ✨ Feature

#46 [Fix] Fix conflict
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Model/QuestionModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Model/QuizModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/QuizViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/OXbuttonView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuiizTitleView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizProgressView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizView.swift
Labels: ✨ Feature

#50 [Add] Color Assets
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/BgPaleBlue.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/BgPaleRed.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/Black10.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/Black20.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/Black40.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/Black50.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/Black60.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/ButtonBlue.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/ButtonRed.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/PointBlueGray.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/PointPaleBlue.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/BG GroupedPrimary.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/BgPrimary.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/PointBlue.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/PointGray.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/PointLine.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(System)/PointRed.colorset/Contents.json
Labels: 🍱 Add

#51 [Fix] fix bookmark check
  ARTX-PoliceScience/ARTX-PoliceScience/Model/QuestionModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookmarkViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/BookmarkViewModel.swift
Labels: ✨ Feature

#53 Fix Color
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/AppDelegate.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/UINavigationController+Util.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookmarkViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/BookmarkView/BookmarkEmptyTableViewCell.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/RegisSettingTableViewCell.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/SettingTableViewCell.swift
Labels: ✨ Feature

#56 Connect HomeView Bookmark View
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookmarkViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/SettingViewController.swift
Labels: ✨ Feature

#57 Fix Unable to Disable Dark Mode
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
Labels: :hammer: Chore

#58 [Feat] init filtering bookmark
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/BookmarkViewModel.swift
Labels: ✨ Feature

#62 Shadow Progressview
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
Labels: ✨ Feature

#60 [Feat] Apply Userdefault
  ARTX-PoliceScience/ARTX-PoliceScience/UserDefault/LocalState.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/BookmarkViewModel.swift
Labels: ✨ Feature

#64 Fix HomeTable Cell separator
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
Labels: :hammer: Chore

#69 Add HomeView Alert Modal
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/AlertText.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/UIAlertController+Util.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeViewAlert.swift
Labels: ✨ Feature

#71 [Chore] Fix JSON file containing questions, explanations, and answers
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/example.json
Labels: :tada: Hotfix

#73 Add and Fix SettingViewAlert
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/AppDelegate.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/AlertText.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/UIAlertController+Util.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/SettingViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/SettingViewAlert.swift
Labels: ✨ Feature

#75 Feature/#36 fix quizview
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookmarkViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HalfModalPresentationController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizModalViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/QuizViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/OXbuttonView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizModalView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizProgressView.swift
Labels: ✨ Feature

#80 Reset UserDefaults
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/AppDelegate.swift
  ARTX-PoliceScience/ARTX-PoliceScience/UserDefault/LocalState.swift
  ARTX-PoliceScience/ARTX-PoliceScience/UserDefault/PartChapter.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/SettingViewAlert.swift
Labels: ✨ Feature

#81 Fix HomeView
  ARTX-PoliceScience/ARTX-PoliceScience/AppDelegate.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Model/QuestionModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/UserDefault/PartChapter.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeViewCell.swift
Labels: ✨ Feature

#87 [feat] Add check chapter count
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookmarkViewController.swift
Labels: :tada: Hotfix

#92 homeview progressbar constraint
  ARTX-PoliceScience/ARTX-PoliceScience/UserDefault/PartChapter.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/SettingViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/SettingViewModel.swift
Labels: ✨ Feature

#102 homeview fix UI detail
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Info.plist
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/Font/GmarketSansTTFBold.ttf
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/Font/GmarketSansTTFLight.ttf
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/Font/GmarketSansTTFMedium.ttf
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/FontStyle.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/HomeViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeViewCell.swift
Labels: ✨ Feature

#101 [Fix] Disable Swipe Back in QuizView
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
Labels: :tada: Hotfix

#106 ToastMessage Delegate
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeViewAlert.swift
Labels: ✨ Feature

#113 Feature/#111 fix json
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Model/QuestionModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/example.json
Labels: :tada: Hotfix

#115 FIx SettingView to HomeView
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/UINavigationController+Util.swift
Labels: :tada: Hotfix

#110 Feature/#109 add bookmarkbutton func in quizview
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookmarkViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizModalViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/QuizViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizModalView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizView.swift
Labels: ✨ Feature

#120 Fix QuizView NavigationView
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
Labels: :tada: Hotfix

#122 Button haptic feedback
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/CustomHaptics.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizModalViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizModalView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizView.swift
Labels: ✨ Feature

#127 Design Detail Check
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/MainViewTop.imageset/BgImage.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/MainViewTop.imageset/BgImage@2x.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/MainViewTop.imageset/BgImage@3x.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/MainViewTop.imageset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/MainViewTop.imageset/MainViewTop@1x.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/MainViewTop.imageset/MainViewTop@2x.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/MainViewTop.imageset/MainViewTop@3x.png
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/AlertText.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/FontStyle.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/UIButton+Util.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/UINavigationController+Util.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/SettingViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/BookTableViewCell.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeView/HomeTableSectionHeaderView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeViewCell.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuiizTitleView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizModalView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizProgressView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizView.swift
Labels: :-1: SlowFix

#130 [Fix] modifying the QuizView, QuizModalView, and BookmarkView
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookmarkViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizModalViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/BookmarkViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeViewAlert.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/OXbuttonView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuiizTitleView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizModalView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizProgressView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizView.swift
Labels: :tada: Hotfix

#132 QuizView UX Fix
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/UINavigationController+Util.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizModalViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizProgressView.swift
Labels: :tada: Hotfix

#135 [Chore] Fix Homeview rerender
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/Color(Custom)/PointRed.colorset/Contents.json
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/MainViewTop.imageset/MainViewTop@1x.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/MainViewTop.imageset/MainViewTop@2x.png
  ARTX-PoliceScience/ARTX-PoliceScience/Assets.xcassets/MainViewTop.imageset/MainViewTop@3x.png
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/UINavigationController+Util.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewModel/BookmarkViewModel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/BookmarkView/BookmarkTableViewCell.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/BookmarkView/SquareBackgroundLabel.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeView/HomeTableCellView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeView/HomeTableHeaderView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeView/HomeTableSectionHeaderView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizProgressView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizTitleView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ko.lproj/LaunchScreen.strings
Labels: :tada: Hotfix

#137 [Chore] Fix progressNumberLabel constraint
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/SettingViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizProgressView.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizTitleView.swift
Labels: :tada: Hotfix

#139 CustomHaptic Fix
  ARTX-PoliceScience/ARTX-PoliceScience/Utils/CustomHaptics.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
Labels: :tada: Hotfix

#141 [Chore] Fix RedLine
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/Resources/example.json
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizModalViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/QuizView/QuizModalView.swift
Labels: :tada: Hotfix

#145 Fix NavigationBar
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/BookmarkViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/SettingViewController.swift
Labels: :tada: Hotfix

#149 [Chore] save theUserdefault user response rate
  ARTX-PoliceScience/ARTX-PoliceScience.xcodeproj/project.pbxproj
  ARTX-PoliceScience/ARTX-PoliceScience/UserDefault/LocalState.swift
  ARTX-PoliceScience/ARTX-PoliceScience/UserDefault/PartChapter.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/HomeViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizModalViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/ViewController/QuizViewController.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/HomeViewAlert.swift
  ARTX-PoliceScience/ARTX-PoliceScience/Views/SettingViewAlert.swift
Labels: :tada: Hotfix
